### PR TITLE
Consider cell heights when finding path

### PR DESCRIPTION
**Pull request by Ali-RS**

### CODE REVIEW

**Comment by MeFisto94** [comment]
Great! Thanks for that. I don't understand why those cells were implemented as 2d objects back then, but we'll see how well it works.

Just one little thing: Instead of `w = new Vector3f(v.x, v.y, v.z);` you can also use `w = v.clone();` or you should also be able to do `w = new Vector3f(v);`. But that doesn't matter, I only wanted to say that :)

**Comment by Ali-RS** [comment]
> Just one little thing: Instead of w = new Vector3f(v.x, v.y, v.z); you can also use w = v.clone(); or you should also be able to do w = new Vector3f(v);. But that doesn't matter, I only wanted to say that :)

Ah, yes... You are right. This didn't come to my mind when i was editing code :smile:  . Maybe it is because I pushed the commit directly on github text editor and not in my dear IDE !! 
Thanks for reminding me.

**Comment by MeFisto94** [comment]
That's dangerous though because you never know if it compiles (e.g. when you forget a `;` or misspell a name). So I'd recommend using the IDE and then maybe later copy&paste (if you don't want to use a local repo) 😃

**Comment by Ali-RS** [comment]
Yes, I promise to do that from now on :blush:

**Pull request merged**
